services:
  db:
    image: mysql:8.0
    container_name: forumhub-mysql
    command: --default-authentication-plugin=caching_sha2_password --mysql-native-password=OFF
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-forumhub}
      MYSQL_USER: ${DB_USERNAME:-forumhub}
      MYSQL_PASSWORD: ${DB_PASSWORD:-ForumHub@2025!}
    ports:
      - "${DB_PORT:-3306}:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u${MYSQL_USER} -p${MYSQL_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: forumhub-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
      SERVER_PORT: ${SERVER_PORT:-8080}

      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-forumhub}
      DB_USERNAME: ${DB_USERNAME:-forumhub}
      DB_PASSWORD: ${DB_PASSWORD:-ForumHub@2025!}

      JWT_SECRET: ${JWT_SECRET:-CHANGE_THIS_SECRET_WITH_32+_CHARS_MIN}
      JWT_EXPIRES: ${JWT_EXPIRES:-3600}

      # Hash BCrypt da senha "1234"
      ADMIN_HASH: ${ADMIN_HASH:-$2a$12$zxdSS44vUMp7LDrsfjubbexDz/mhZ93jkk3t3/Dv22lYQvAeI045e}
    ports:
      - "${SERVER_PORT:-8080}:8080"
